In [1]:
import numpy as np

In [2]:
a=[1,2,3]

In [3]:
type(a)

list

In [4]:
b=np.array(a)

In [5]:
b

array([1, 2, 3])

In [6]:
type(b)

numpy.ndarray

In [7]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [10]:
#linspace is always taken as float

In [11]:
np.linspace(0,3,31)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ])

In [12]:
#one question for test maybe

In [13]:
c=[[1,2,3],[10,20,30]]

In [14]:
np.array(c)

array([[ 1,  2,  3],
       [10, 20, 30]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(c) #it says list not array

list

In [18]:
#when u put in np array it becomes an array

In [22]:
np.zeros((3,4)) #put two brackets for this

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4)) #for multidimenstional argument use tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
first_thirty = np.linspace(0,29,30)

In [31]:
print(first_thirty)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]


In [33]:
first_thirty.shape #it is method not function because no brackets

(30,)

In [36]:
first_thirty.shape() #error because it is not function therefore it is a method

TypeError: 'tuple' object is not callable

In [37]:
#lets say in this array i wanna divide to three arrays

In [42]:
first_thirty.reshape(3,10) #3 rows and 10 cols 

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [43]:
#linspace, shape, reshape question will come (5 marks)

In [44]:
#creating numpy

In [46]:
#selecting from numpy array may come

In [47]:
import numpy as np

In [48]:
first_ten= np.arange(0,10)

In [49]:
print(first_ten)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
first_ten[3]

3

In [52]:
first_ten[3:5] #starting from index 3 including to index 5 (excluding)

array([3, 4])

In [54]:
first_ten[:2] #starting from beginning

array([0, 1])

In [55]:
first_ten[6:]

array([6, 7, 8, 9])

In [59]:
three_ten= first_thirty.reshape(3,10)
three_by_ten

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [60]:
first_thirty= np.linspace(0,29,30)
three_by_ten=first_thirty.reshape(3,10)
print(three_by_ten)
print(three_by_ten.shape)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]
(3, 10)


In [61]:
three_by_ten[1] #only first row data is printed thats why it is important to define as diff name (variabke)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [62]:
three_by_ten[0] #first row takes (0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
three_by_ten[1,5] #prints 1st row and 5th index 

15.0

In [64]:
three_by_ten[0:2,1:3] #this takes from row 1 (index 0) and value index 2 

array([[ 1.,  2.],
       [11., 12.]])

In [65]:
#u can shift tab to refer to the table array

In [67]:
tens=np.arange(0,101,10) #from 0 included to 101 excluded in steps of 10
print(tens)

[  0  10  20  30  40  50  60  70  80  90 100]


In [69]:
tens=np.arange(0,101)

In [70]:
print(tens)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [71]:
tens >=60

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [72]:
tens[6:]

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100])